apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestures-ui
  labels:
    app: gestures-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestures-ui
  template:
    metadata:
      labels:
        app: gestures-ui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - cpu
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: gestures-ui
          image: ghcr.io/aihpi/demo-visionary-gestures:sha-a6730a4
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"



